
title: "RDU 2017"
description: "Raleigh-Durham Test Drive"
permalink: ':title/'

markdown: kramdown
baseurl: "/raleigh-durham"


sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
#analytics: UA-...

# Comments
disqus-shortname: coxtrevor

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]
